<?php

namespace Tests\Unit;

use App\Order;
use App\Product;

class OrderTest extends \PHPUnit_Framework_TestCase 
{

	 protected $order;
	 
	 function setUp()
	 {
		  $order = new Order;
		  $this->order = $order;

		  $product = new Product('Fallout 4', 60);
		  $product2= new Product('Pillow', 10);

		  $this->order->add($product);
		  $this->order->add($product2);
		  parent::setUp(); // TODO: Change the autogenerated stub
	 }

	 /**
	  * @test
	  */
	 function an_order_consists_of_products() 
	 {
//	 	 $this->assertEquals(2, count($order->products()));
	 	 $this->assertCount(2, $this->order->products());
	 	 
	 }
	 
	 /**
	  * @test
	  */
	 function an_order_can_determine_the_total_cost_of_all_its_products()
	 {
	 	 $this->assertEquals(70, $this->order->total());
	 }
}