<?php

namespace Tests\Unit;

use App\Product;

class ProductTest extends \PHPUnit_Framework_TestCase 
{
	 protected $product;

	 /**
	  * the setup function will be executed with every phpunit call.
	  * this allows you to set data used by many tests. When grouping your tests by model, etc.
	  * this can be very useful
	  */
	 function setUp() {
		  $this->product = new Product('Fallout 4', 60.00);
		  parent::setUp(); // TODO: Change the autogenerated stub
	 }

	 /**
	  * It is a good practice to speak your tests out before writing the code.
	  * This will solidify the semantics and make it clear about what you are testing.
	  */

	 /**
	  * @test 
	  */
	 function a_product_has_a_name()
	 {
	 	 
	 	 $this->assertEquals('Fallout 4', $this->product->name);
	 }
	 
	 /**
	  * @test
	  */
	 function a_product_has_price()
	 {
	 	 $this->assertInternalType('float', $this->product->price);
	 }
}